# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=20)),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'As',
                'verbose_name': 'A',
                'ordering': ['id'],
            },
        ),
    ]
